import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.type() + ': ' + m.text().slice(0, 300)) })
const t0 = Date.now()
await page.goto('http://localhost:3100/?perf=1', { waitUntil: 'domcontentloaded' })
await page.waitForSelector('[role="grid"] [role="gridcell"]', { timeout: 60000 })
console.log('grid ready in', Date.now() - t0, 'ms')
console.log('live text:', await page.locator('[aria-live="polite"]').first().textContent())
console.log('kpis:', await page.locator('dl dd').allTextContents())
console.log('first row:', (await page.locator('[role="row"][aria-rowindex="2"] [role="gridcell"]').allTextContents()).join(' | '))
await page.screenshot({ path: process.env.SHOT || '/tmp/claude-1000/-home-guilhermerabelo-Documents-rabelo-data-heavy-dashboard/ac402854-f208-4039-9bf4-abc7679d0b28/scratchpad/smoke.png', fullPage: true })
// interaction: sort by pago
await page.getByRole('button', { name: 'Paid' }).first().click()
await page.waitForTimeout(500)
await page.getByLabel('Search budget lines by agency, program, action or element').fill('universidade')
await page.waitForTimeout(800)
console.log('after search:', await page.locator('[aria-live="polite"]').first().textContent())
console.log('perfLog:', JSON.stringify(await page.evaluate(() => (window.__perfLog || []).map(e => ({ n: e.name, ms: +e.ms.toFixed(1), eng: e.engineMs && +e.engineMs.toFixed(1), rows: e.rows })))))
console.log('url:', page.url())
console.log('errors:', errors.length ? errors.join('\n') : 'none')
await browser.close()
