/**
 * Renders the README "Data defects" table from public/data/v1/defects-report.json
 * between the <!-- defects:start --> / <!-- defects:end --> markers.
 * Run: pnpm readme:defects
 */
import fs from 'node:fs'
import path from 'node:path'
import type { DefectsReport, DefectResult } from '../../types/dataset.ts'
import { OUT_DIR, ROOT } from '../pipeline/config.ts'

const report = JSON.parse(fs.readFileSync(path.join(OUT_DIR, 'defects-report.json'), 'utf8')) as DefectsReport
const readmePath = path.join(ROOT, 'README.md')

const n = (x: number) => x.toLocaleString('en-US')
const pct = (part: number, whole: number) => (whole === 0 ? '—' : `${((100 * part) / whole).toFixed(part === whole ? 0 : 1)}%`)
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ')

const ACTION_LABEL: Record<DefectResult['action'], string> = {
  transform: 'transformed',
  nullify: 'set to null',
  'drop-row': 'row dropped',
  'drop-column': 'column dropped',
  keep: 'kept as-is',
  document: 'documented',
}

function rowsCell(r: DefectResult): string {
  const years = report.years.map(String)
  const total = years.reduce((s, y) => s + (r.affectedRows[y] ?? 0), 0)
  const kept = years.reduce((s, y) => s + (report.keptRows[y] ?? 0), 0)
  const input = years.reduce((s, y) => s + (report.inputRows[y] ?? 0), 0)
  if (total === 0) return 'dictionary-level (see notes)'
  const perYear = years.map((y) => `${y}: ${n(r.affectedRows[y] ?? 0)}`).join(', ')
  // rules that run before DEF-17 count every input row
  return `${n(total)} (${pct(total, total > kept ? input : kept)}) — ${perYear}`
}

function exampleCell(r: DefectResult): string {
  const e = r.examples[0]
  if (!e) return r.notes[0] ? cell(r.notes[0].length > 110 ? r.notes[0].slice(0, 107) + '…' : r.notes[0]) : '—'
  const before = cell(e.before.length > 70 ? e.before.slice(0, 67) + '…' : e.before)
  return e.after === null || e.after === undefined ? `\`${before}\`` : `\`${before}\` → \`${cell(e.after.length > 60 ? e.after.slice(0, 57) + '…' : e.after)}\``
}

const years = report.years.map(String)
const totalIn = years.reduce((s, y) => s + report.inputRows[y], 0)
const totalKept = years.reduce((s, y) => s + report.keptRows[y], 0)
const totalDropped = years.reduce((s, y) => s + report.droppedRows[y], 0)

const lines: string[] = []
lines.push(
  `Input: **${n(totalIn)} rows** (${years.map((y) => `${y}: ${n(report.inputRows[y])}`).join(', ')}). ` +
    `Kept: **${n(totalKept)}**. Dropped: **${n(totalDropped)}** (${pct(totalDropped, totalIn)}), all by DEF-17 and nothing else. ` +
    `Counts below are over kept rows unless the rule runs before DEF-17.`,
)
lines.push('')
lines.push('| ID | Defect | Rule applied | Action | Rows affected | Example |')
lines.push('| --- | --- | --- | --- | --- | --- |')
for (const r of report.rules) {
  lines.push(`| ${r.id} | **${cell(r.title)}** — ${cell(r.problem)} | ${cell(r.rule)} | ${ACTION_LABEL[r.action]} | ${rowsCell(r)} | ${exampleCell(r)} |`)
}
lines.push('')
const notes = report.rules.filter((r) => r.notes.length > 0)
if (notes.length) {
  lines.push('<details><summary>Per-year notes generated by the pipeline</summary>')
  lines.push('')
  for (const r of notes) {
    lines.push(`**${r.id}**`)
    lines.push('')
    for (const t of r.notes) lines.push(`- ${cell(t)}`)
    lines.push('')
  }
  lines.push('</details>')
}

const readme = fs.readFileSync(readmePath, 'utf8')
const start = '<!-- defects:start -->'
const end = '<!-- defects:end -->'
const a = readme.indexOf(start)
const b = readme.indexOf(end)
if (a < 0 || b < 0 || b < a) throw new Error('README.md is missing the defects markers')
const next = readme.slice(0, a + start.length) + '\n' + lines.join('\n') + '\n' + readme.slice(b)
fs.writeFileSync(readmePath, next)
console.log(`README defects table: ${report.rules.length} rules, ${n(totalIn)} input rows`)
